Bugfix/School 407/make-up-the-where-to-start-page
LamArt/open-schools-platform-frontend pull request #105
Opened 2023-01-31 12:56 UTC by Tohenzoo

2023-02-12 17:36 UTC, gaskeo requested changes

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/Tittle.tsx
> +import Layout from "../../components/layouts/layout";
unused import

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/Tittle.tsx
> +function Tittle() {
It's typo in word `Title` (in file name too)

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/WhereToStart.tsx
> +import { Steps, List, Avatar } from 'antd';
unused imports

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/WhereToStart.tsx
> +    title: <div><div className={styles.listMain}>Создание организации</div><div className={styles.listChildren}>Добавляйте свои организации, чтобы получить доступ ко всем функциям. </div></div>,
move inline css in scss file

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/index.tsx
> +const { Title } = Typography;
unused const

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/index.tsx
> +import { Switch, Typography } from "antd";
unused imports

2023-02-12 17:36 UTC, gaskeo commented on components/WhereToStartPageComponents/styles/wtsp.module.css
> +.title {
we use scss preprocessor

2023-02-12 17:36 UTC, gaskeo commented on package.json
> +  "version": "1.22.20"
why it's 1.22.20 version number?

2023-02-12 17:36 UTC, gaskeo commented on pages/whereToStartPage/index copy.tsx
> +import Layout from "../../components/layouts/layout";
this file unused

2023-02-14 06:03 UTC, dowlsss approved these changes

2023-02-14 06:47 UTC, gaskeo approved these changes

2023-02-14 06:49 UTC, merged