Fix/fix bugs validation
LamArt/open-schools-platform-frontend pull request #124
Opened 2023-03-23 22:31 UTC by Rey-2903

2023-03-28 12:49 UTC, zavarin-michael requested changes

2023-03-28 12:49 UTC, zavarin-michael commented on .vscode/launch.json
> +}
explain?
i would not add this file in repo

2023-03-28 12:49 UTC, zavarin-michael commented on components/CirclesComponents/CircleCreateForm.tsx
> +                            whitespace: true,
should it be false?
i think user shouldn't eneter any whitespace in this input

2023-03-28 12:49 UTC, zavarin-michael commented on components/EmployeeComponents/AddEmployee.tsx
> +                                whitespace: true,
^^

2023-03-29 18:53 UTC, Rey-2903 commented on components/CirclesComponents/CircleCreateForm.tsx
> +                            whitespace: true,
The white space parameter in the antd library is responsible for checking for entering spaces, so it has the value true

2023-03-29 18:54 UTC, Rey-2903 commented on .vscode/launch.json
> +}
Deleted this file

2023-03-30 10:11 UTC, zavarin-michael approved these changes

2023-03-30 10:12 UTC, merged