School 397 добавление препроцессора scss
LamArt/open-schools-platform-frontend pull request #58
Opened 2022-10-21 08:32 UTC by Rey-2903

2022-10-31 10:43 UTC, gaskeo commented
CI build failed on `npm install yarn` command. On CI we use **node v16.x**, that can't be used with **node-sass v7.0.3**. You need to specify valid version of **node-sass** for our version of **node**. 

You can check all available versions of **node-sass** with this command: `npm view node-sass version`.

[Version compatibility of **node** and **node-sass**](https://www.npmjs.com/package/node-sass#Node-version-support-policy)

2022-10-31 10:44 UTC, gaskeo requested changes

2022-10-31 10:44 UTC, gaskeo commented on assets/styles/variables.scss
> +    margin: 0px 20px 16px 20px;
no need to write **px** when the value is **0**

2022-10-31 10:44 UTC, gaskeo commented on assets/styles/variables.scss
> +    margin: 8px 8px 8px 0px;
no need to write **px** when the value is **0** (`0px -> 0`)

2022-10-31 10:44 UTC, gaskeo commented on assets/styles/variables.scss
> +    font-family: 'Open Sans';
Add generic family name: `'Open Sans' -> 'Open Sans', sans-serif` (and in **h2** tag too). 
It's good practice: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

2022-10-31 10:44 UTC, gaskeo commented on components/components styles/EmployeeList.module.scss
> +    @extend %components;
I can't find `%components` in **variables.scss**, maybe it's missed?

2022-10-31 10:44 UTC, gaskeo commented on components/QueryComponents/QueryList.module.scss
> +@import '../../../assets/styles/variables.scss';
`../../..` from this directory goes to directory, that doesn't contain **assets** folder. Maybe need `../..`?

2022-10-31 11:15 UTC, JIiCeHoK commented on assets/styles/variables.scss
> +    margin: 8px 8px 8px 0px;
Разницы нет. Можно и так оставить

2022-11-01 14:53 UTC, gaskeo approved these changes

2022-11-01 14:54 UTC, merged