Add: layout of the page for adding a circle
LamArt/open-schools-platform-frontend pull request #65
Opened 2022-11-11 10:24 UTC by Rey-2903

2022-11-14 09:01 UTC, AnnaErs reviewed
Combine circle info and the table. They have different intends now, they need to be corrected

2022-11-14 09:53 UTC, gaskeo requested changes

2022-11-14 09:53 UTC, gaskeo commented on components/CirclesComponents/CircleInfo.tsx
> +import styles from './styles/CircleInfo.module.scss';
use `style` variable name like in other places

2022-11-14 09:53 UTC, gaskeo commented on components/CirclesComponents/CircleInfo.tsx
> +                                <div className={`${styles.text} ${styles.title_information}`}>
we use [camelCase](https://en.wikipedia.org/wiki/Camel_case) in our `scss` styles (with first lowercase letter). Change class names to this style (`title_information -> titleInformation`) in this and other places

2022-11-14 09:53 UTC, gaskeo commented on components/QueryComponents/QueryChangeView.tsx
> +                                        options={[
Take out options array to `const` beyond `QueryChangeView` component. This will be more readable (`options={options}`)

2022-11-14 09:53 UTC, gaskeo commented on components/StudentComponents/StudentCircleList.tsx
> +import styles from './styles/StudentCircleList.module.scss';
use `style` variable name

2022-11-18 05:11 UTC, gaskeo requested changes

2022-11-18 05:11 UTC, gaskeo commented on assets/styles/variables.scss
> +%titleСontainer {
You use Cyrillic `C` in titleContainer. Change this to Latin `C`

2022-11-19 12:41 UTC, gaskeo approved these changes

2022-11-23 12:05 UTC, closed without merging