fix: the architecture of person card
LamArt/open-schools-platform-frontend pull request #68
Opened 2022-11-15 20:02 UTC by AnnaErs

2022-11-18 04:26 UTC, gaskeo requested changes

2022-11-18 04:26 UTC, gaskeo commented on components/MicsComponents/TableData.tsx
> +    data: Record<string, string | undefined>;
If we need bold text in some place, for example, we won't be able to do this because `<b>text</b>` isn't `string` type. Besides it in component we call any key of type `string`, this can cause bags (key not found), construction `TABLE_LABELS[key] || key` doesn't help because it is hard and can cause bags too. 

I think we can create other construction, for example: 
```
interface Props {
    data: { key: React.ReactNode, value: React.ReactNode }[];
}
```

In this construction we know all keys (`data`, `key`, `value`) and developers can use this construction wider, for example: 
```
onst p: Props = {data: [{key: "<i>Italian text</i>", value: <b>Bold text</b>}]}

<TableData data={p}>
```
* With strings this example works fine too.

2022-11-18 04:26 UTC, gaskeo commented on components/MicsComponents/TableData.tsx
> +const TABLE_LABELS: Record<string, string> = {
I think we don't need this structure, because developers can pass any data in this component. For example, if developer creates prop with key `position` and this key isn't describes post in organization, he receive an bug because we replace his key with our key `Должность`.

2022-11-18 04:26 UTC, gaskeo commented on components/MicsComponents/TableData.tsx
> +                        .filter(([key, value]) => Boolean(value))
If we use other structure with required `value` key, we can not to do this filter.

2022-11-18 04:26 UTC, gaskeo commented on pages/api/employee-info.ts
> +export const getEmployeee = () => {
Typo in `Employeee` (last `e`)

2022-11-18 04:26 UTC, gaskeo commented on pages/api/employee-info.ts
> +    //здесь будет запрос сотрудника
I think, we need to write comments in English.

2022-11-18 04:26 UTC, gaskeo commented on utils/phoneConverter.ts
> +export const cleanedPhoneNumber = (phoneNumberString: string | undefined) => {
in this function we clean phone number, I think this function shouldn't check if phone is undefined. Functions must do only one thing that declares in its name. `phoneNumberString` must be `string` type only. Developers must send phone number in `string` format. They can check if they have phone number or `undefined` (`cleanedPhoneNumber(myPhone || '')`)

2022-11-23 20:09 UTC, AnnaErs commented on components/MicsComponents/TableData.tsx
> +                        .filter(([key, value]) => Boolean(value))
This is a generic component, this filter checks if value exists

2022-11-23 20:14 UTC, AnnaErs commented on components/MicsComponents/TableData.tsx
> +    data: Record<string, string | undefined>;
The current design does not yet imply this. I see no reason to complicate, for the sake of what is not required now

2022-11-23 20:25 UTC, AnnaErs commented on components/MicsComponents/TableData.tsx
> +const TABLE_LABELS: Record<string, string> = {
I don't see the point in such strict typing. This is a common structure for student and staff that describes the structure of their table

2022-11-28 08:54 UTC, gaskeo requested changes

2022-11-28 08:54 UTC, gaskeo commented on components/MicsComponents/TableDataEdit.tsx
> +import { Button, Form, Input } from "antd";
Unused `Form` import

2022-11-28 08:54 UTC, gaskeo commented on pages/employee/[id]/index.tsx
> +export default function EmpoyeeProfile() {
Typo: Emp**l**oyee

2022-12-01 08:00 UTC, gaskeo approved these changes

2022-12-01 08:00 UTC, merged