rename branch
LamArt/open-schools-platform-frontend pull request #71
Opened 2022-11-20 07:28 UTC by LeonidErshov

2022-11-21 09:20 UTC, IlyaBat9 commented on components/AnalyticsComponents/ReportsComponents.tsx
> +  { title: "Закрыты", number: 0 },
Wrong language

2022-11-21 09:21 UTC, IlyaBat9 commented on components/AnalyticsComponents/ReportsComponents.tsx
> +    label: "год",
Language

2022-11-21 09:24 UTC, IlyaBat9 requested changes
One problem

2022-11-21 09:24 UTC, IlyaBat9 commented on pages/analytics/index.tsx
>  // Изменить название функции index на Analytics --done
Delete comment

2022-11-24 18:42 UTC, AnnaErs approved these changes

2022-11-28 07:14 UTC, gaskeo requested changes

2022-11-28 07:14 UTC, gaskeo commented on components/AnalyticsComponents/style/ReportsComponents.module.css
> +.container{
Need space between `container` and `{`

2022-11-28 07:14 UTC, gaskeo commented on components/AnalyticsComponents/style/ReportsComponents.module.css
> +.box_header {
We use `camelCase` naming for classes because we import them into JS code. Change all classes from `snake_case` to `camelCase`

2022-11-28 07:14 UTC, gaskeo commented on pages/analytics/index.tsx
> +import React, {useState, useEffect} from "react";
Delete unused `useState` and `useEffect` imports.

2022-12-02 11:07 UTC, IlyaBat9 commented on components/AnalyticsComponents/ReportsComponents.tsx
> +    label: "год",
^^

2022-12-02 11:22 UTC, LeonidErshov commented on components/AnalyticsComponents/ReportsComponents.tsx
> +  { title: "Закрыты", number: 0 },
have you decided to leave it like this?

2022-12-02 11:23 UTC, LeonidErshov commented on pages/analytics/index.tsx
>  // Изменить название функции index на Analytics --done
done

2022-12-02 12:07 UTC, IlyaBat9 commented on components/AnalyticsComponents/ReportsComponents.tsx
> +  { title: "Закрыты", number: 0 },
I don't know.

2022-12-02 18:53 UTC, IlyaBat9 approved these changes

2022-12-05 08:02 UTC, merged